# Generated by Django 4.2.4 on 2023-09-05 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_name", models.CharField(max_length=255, unique=True)),
                ("address", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(default="Default Title")),
                (
                    "project_cover_image",
                    models.FileField(
                        blank=True, null=True, upload_to="project_images/"
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("concluded_on", models.DateTimeField(blank=True, null=True)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("general", "General public (any age)"),
                            ("target", "Particular target Audience (Please specify)"),
                            ("adults", "Adults"),
                            ("tertiary", "Tertiary students"),
                            ("high_school", "High school age"),
                            ("primary_school", "Primary School age"),
                            ("early_years", "Early years"),
                            ("adults_60", "Adults >60 please"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "delivery_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("biannually", "Biannually"),
                            ("annually", "Annually"),
                            ("ongoing", "Ongoing"),
                            ("once", "Once"),
                            ("irregular", "Opportunistic/Irregularly"),
                            ("on_demand", "Permanent/On demand"),
                        ],
                        max_length=20,
                    ),
                ),
                ("language", models.TextField()),
                ("format", models.TextField()),
                ("web_link", models.TextField()),
                ("policy_link", models.TextField()),
                ("results", models.TextField(blank=True, max_length=150)),
                ("lessons_learned", models.TextField(blank=True, max_length=100)),
                ("key_messages", models.CharField(blank=True, max_length=50)),
                ("relationship_to_rce_activities", models.TextField(blank=True)),
                ("funding", models.TextField(blank=True)),
                (
                    "priority_area_1",
                    models.CharField(
                        blank=True,
                        choices=[("direct", "Direct"), ("indirect", "Indirect")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "priority_area_2",
                    models.CharField(
                        blank=True,
                        choices=[("direct", "Direct"), ("indirect", "Indirect")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "priority_area_3",
                    models.CharField(
                        blank=True,
                        choices=[("direct", "Direct"), ("indirect", "Indirect")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "priority_area_4",
                    models.CharField(
                        blank=True,
                        choices=[("direct", "Direct"), ("indirect", "Indirect")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "priority_area_5",
                    models.CharField(
                        blank=True,
                        choices=[("direct", "Direct"), ("indirect", "Indirect")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "disaster_risk_reduction",
                    models.CharField(
                        blank=True,
                        choices=[("direct", "Direct"), ("indirect", "Indirect")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "traditional_knowledge",
                    models.CharField(
                        blank=True,
                        choices=[("direct", "Direct"), ("indirect", "Indirect")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "agriculture",
                    models.CharField(
                        blank=True,
                        choices=[("direct", "Direct"), ("indirect", "Indirect")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "arts",
                    models.CharField(
                        blank=True,
                        choices=[("direct", "Direct"), ("indirect", "Indirect")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "curriculum_development",
                    models.CharField(
                        blank=True,
                        choices=[("direct", "Direct"), ("indirect", "Indirect")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "ecotourism",
                    models.CharField(
                        blank=True,
                        choices=[("direct", "Direct"), ("indirect", "Indirect")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "forests_trees",
                    models.CharField(
                        blank=True,
                        choices=[("direct", "Direct"), ("indirect", "Indirect")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "plants_animals",
                    models.CharField(
                        blank=True,
                        choices=[("direct", "Direct"), ("indirect", "Indirect")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "waste",
                    models.CharField(
                        blank=True,
                        choices=[("direct", "Direct"), ("indirect", "Indirect")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "affiliations",
                    models.ManyToManyField(
                        related_name="affiliated_projects", to="UNRCE_APP.organisation"
                    ),
                ),
                (
                    "contributing_organizations",
                    models.ManyToManyField(
                        related_name="contributing_projects",
                        to="UNRCE_APP.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RCEHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hub_name", models.CharField(max_length=255)),
                ("contact_info", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SDG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sdg",
                    models.CharField(
                        choices=[
                            ("goal_1", "Goal 1"),
                            ("goal_2", "Goal 2"),
                            ("goal_3", "Goal 3"),
                            ("goal_4", "Goal 4"),
                            ("goal_5", "Goal 5"),
                            ("goal_6", "Goal 6"),
                            ("goal_7", "Goal 7"),
                            ("goal_8", "Goal 8"),
                            ("goal_9", "Goal 9"),
                            ("goal_10", "Goal 10"),
                            ("goal_11", "Goal 11"),
                            ("goal_12", "Goal 12"),
                            ("goal_13", "Goal 13"),
                            ("goal_14", "Goal 14"),
                            ("goal_15", "Goal 15"),
                            ("goal_16", "Goal 16"),
                            ("goal_17", "Goal 17"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectSDG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[("direct", "Direct"), ("indirect", "Indirect")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UNRCE_APP.project",
                    ),
                ),
                (
                    "sdg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UNRCE_APP.sdg"
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "sdg")},
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="project_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UNRCE_APP.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="project_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UNRCE_APP.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="files",
            field=models.ManyToManyField(
                related_name="projects", to="UNRCE_APP.projectfile"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="images",
            field=models.ManyToManyField(
                related_name="projects", to="UNRCE_APP.projectimage"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="manager",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="sdgs",
            field=models.ManyToManyField(
                through="UNRCE_APP.ProjectSDG", to="UNRCE_APP.sdg"
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="hub",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="UNRCE_APP.rcehub"
            ),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                ("image", models.ImageField(max_length=36, upload_to="")),
                ("uploaded_date", models.DateTimeField()),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "followed_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UNRCE_APP.project",
                    ),
                ),
                (
                    "following_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
