# Generated by Django 4.2.4 on 2023-09-05 04:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("UNRCE_APP", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="manager",
            new_name="user",
        ),
    ]
