# Generated by Django 4.2.4 on 2023-09-05 04:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("UNRCE_APP", "0002_rename_manager_project_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="user",
        ),
    ]
