# Generated by Django 4.2.4 on 2023-09-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UNRCE_APP", "0002_alter_project_lessons_learned_alter_sdg_sdg"),
    ]

    operations = [
        migrations.AddField(
            model_name="sdg",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="sdg",
            name="sdg",
            field=models.CharField(
                choices=[
                    ("goal_1", "End poverty in all its forms everywhere"),
                    (
                        "goal_2",
                        "End hunger, achieve food security and improved nutrition and promote sustainable agriculture",
                    ),
                    (
                        "goal_3",
                        "Ensure healthy lives and promote well-being for all at all ages",
                    ),
                    (
                        "goal_4",
                        "Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all",
                    ),
                    (
                        "goal_5",
                        "Achieve gender equality and empower all women and girls",
                    ),
                    (
                        "goal_6",
                        "Ensure availability and sustainable management of water and sanitation for all",
                    ),
                    (
                        "goal_7",
                        "Ensure access to affordable, reliable, sustainable and modern energy for all",
                    ),
                    (
                        "goal_8",
                        "Promote sustained, inclusive and sustainable economic growth, full and productive employment and decent work for all",
                    ),
                    (
                        "goal_9",
                        "Build resilient infrastructure, promote inclusive and sustainable industrialization and foster innovation",
                    ),
                    ("goal_10", "Reduce inequality within and among countries"),
                    (
                        "goal_11",
                        "Make cities and human settlements inclusive, safe, resilient and sustainable",
                    ),
                    (
                        "goal_12",
                        "Ensure sustainable consumption and production patterns",
                    ),
                    (
                        "goal_13",
                        "Take urgent action to combat climate change and its impacts",
                    ),
                    (
                        "goal_14",
                        "Conserve and sustainably use the oceans, seas and marine resources for sustainable development",
                    ),
                    (
                        "goal_15",
                        "Protect, restore and promote sustainable use of terrestrial ecosystems, sustainably manage forests, combat desertification, and halt and reverse land degradation and halt biodiversity loss",
                    ),
                    (
                        "goal_16",
                        "Promote peaceful and inclusive societies for sustainable development, provide access to justice for all and build effective, accountable and inclusive institutions at all levels",
                    ),
                    (
                        "goal_17",
                        "Strengthen the means of implementation and revitalize the Global Partnership for Sustainable Development",
                    ),
                ],
                max_length=10,
            ),
        ),
    ]
