# Generated by Django 4.2.4 on 2023-08-30 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("UNRCE_APP", "0003_project_delete_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="RCEHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hub_name", models.CharField(max_length=255)),
                ("contact_info", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SDG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sdg",
                    models.CharField(
                        choices=[
                            ("goal_1", "Goal 1"),
                            ("goal_2", "Goal 2"),
                            ("goal_3", "Goal 3"),
                            ("goal_4", "Goal 4"),
                            ("goal_5", "Goal 5"),
                            ("goal_6", "Goal 6"),
                            ("goal_7", "Goal 7"),
                            ("goal_8", "Goal 8"),
                            ("goal_9", "Goal 9"),
                            ("goal_10", "Goal 10"),
                            ("goal_11", "Goal 11"),
                            ("goal_12", "Goal 12"),
                            ("goal_13", "Goal 13"),
                            ("goal_14", "Goal 14"),
                            ("goal_15", "Goal 15"),
                            ("goal_16", "Goal 16"),
                            ("goal_17", "Goal 17"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="project",
            name="manager",
        ),
        migrations.AddField(
            model_name="project",
            name="agriculture",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("direct", "Direct"),
                    ("indirect", "Indirect"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="arts",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("direct", "Direct"),
                    ("indirect", "Indirect"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="curriculum_development",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("direct", "Direct"),
                    ("indirect", "Indirect"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="disaster_risk_reduction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("direct", "Direct"),
                    ("indirect", "Indirect"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="ecotourism",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("direct", "Direct"),
                    ("indirect", "Indirect"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="forests_trees",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("direct", "Direct"),
                    ("indirect", "Indirect"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="funding",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="key_messages",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="lessons_learned",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="plants_animals",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("direct", "Direct"),
                    ("indirect", "Indirect"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="priority_area_1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("direct", "Direct"),
                    ("indirect", "Indirect"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="priority_area_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("direct", "Direct"),
                    ("indirect", "Indirect"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="priority_area_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("direct", "Direct"),
                    ("indirect", "Indirect"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="priority_area_4",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("direct", "Direct"),
                    ("indirect", "Indirect"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="priority_area_5",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("direct", "Direct"),
                    ("indirect", "Indirect"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="relationship_to_rce_activities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="results",
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="project",
            name="title",
            field=models.TextField(default="Default Title"),
        ),
        migrations.AddField(
            model_name="project",
            name="traditional_knowledge",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("direct", "Direct"),
                    ("indirect", "Indirect"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="waste",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("direct", "Direct"),
                    ("indirect", "Indirect"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="audience",
            field=models.CharField(
                choices=[
                    ("general", "General public (any age)"),
                    ("target", "Particular target Audience (Please specify)"),
                    ("adults", "Adults"),
                    ("tertiary", "Tertiary students"),
                    ("high_school", "High school age"),
                    ("primary_school", "Primary School age"),
                    ("early_years", "Early years"),
                    ("adults_60", "Adults >60 please"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="delivery_frequency",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("biannually", "Biannually"),
                    ("annually", "Annually"),
                    ("ongoing", "Ongoing"),
                    ("once", "Once"),
                    ("irregular", "Opportunistic/Irregularly"),
                    ("on_demand", "Permanent/On demand"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProjectSDG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UNRCE_APP.project",
                    ),
                ),
                (
                    "sdg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UNRCE_APP.sdg"
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "sdg")},
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UNRCE_APP.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_name", models.CharField(max_length=255, unique=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UNRCE_APP.rcehub",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "followed_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UNRCE_APP.project",
                    ),
                ),
                (
                    "following_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_address", models.EmailField(max_length=254, unique=True)),
                ("receives_notifications", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Affiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authenticated", models.BooleanField(default=False)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UNRCE_APP.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="contributing_organizations",
            field=models.ManyToManyField(to="UNRCE_APP.organisation"),
        ),
        migrations.AddField(
            model_name="project",
            name="sdgs",
            field=models.ManyToManyField(
                through="UNRCE_APP.ProjectSDG", to="UNRCE_APP.sdg"
            ),
        ),
        migrations.CreateModel(
            name="ProjectPartnerCompanies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "partner_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UNRCE_APP.organisation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UNRCE_APP.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "partner_company")},
            },
        ),
    ]
