# Generated by Django 4.2.4 on 2023-09-05 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("UNRCE_APP", "0003_remove_project_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="manager",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
