# Generated by Django 4.2.4 on 2023-09-05 05:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("UNRCE_APP", "0004_project_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="manager",
        ),
    ]
