# Generated by Django 4.2.4 on 2023-09-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UNRCE_APP", "0004_project_approval_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="interested_projects",
            field=models.ManyToManyField(
                blank=True, related_name="users_interested", to="UNRCE_APP.project"
            ),
        ),
    ]
