# Generated by Django 4.2.4 on 2023-09-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UNRCE_APP", "0005_projectfile_projectimage_remove_post_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsdg",
            name="relationship_type",
            field=models.CharField(
                choices=[("direct", "Direct"), ("indirect", "Indirect")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="agriculture",
            field=models.CharField(
                blank=True,
                choices=[("direct", "Direct"), ("indirect", "Indirect")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="arts",
            field=models.CharField(
                blank=True,
                choices=[("direct", "Direct"), ("indirect", "Indirect")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="curriculum_development",
            field=models.CharField(
                blank=True,
                choices=[("direct", "Direct"), ("indirect", "Indirect")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="disaster_risk_reduction",
            field=models.CharField(
                blank=True,
                choices=[("direct", "Direct"), ("indirect", "Indirect")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="ecotourism",
            field=models.CharField(
                blank=True,
                choices=[("direct", "Direct"), ("indirect", "Indirect")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="forests_trees",
            field=models.CharField(
                blank=True,
                choices=[("direct", "Direct"), ("indirect", "Indirect")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="plants_animals",
            field=models.CharField(
                blank=True,
                choices=[("direct", "Direct"), ("indirect", "Indirect")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="priority_area_1",
            field=models.CharField(
                blank=True,
                choices=[("direct", "Direct"), ("indirect", "Indirect")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="priority_area_2",
            field=models.CharField(
                blank=True,
                choices=[("direct", "Direct"), ("indirect", "Indirect")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="priority_area_3",
            field=models.CharField(
                blank=True,
                choices=[("direct", "Direct"), ("indirect", "Indirect")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="priority_area_4",
            field=models.CharField(
                blank=True,
                choices=[("direct", "Direct"), ("indirect", "Indirect")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="priority_area_5",
            field=models.CharField(
                blank=True,
                choices=[("direct", "Direct"), ("indirect", "Indirect")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="traditional_knowledge",
            field=models.CharField(
                blank=True,
                choices=[("direct", "Direct"), ("indirect", "Indirect")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="waste",
            field=models.CharField(
                blank=True,
                choices=[("direct", "Direct"), ("indirect", "Indirect")],
                default="",
                max_length=10,
            ),
        ),
    ]
