# Generated by Django 4.2.4 on 2023-09-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UNRCE_APP", "0005_customuser_interested_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="interested_sdgs",
            field=models.ManyToManyField(
                related_name="interested_users", to="UNRCE_APP.sdg"
            ),
        ),
    ]
