# Generated by Django 4.2.4 on 2023-09-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UNRCE_APP", "0006_projectsdg_relationship_type_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectpartnercompanies",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="projectpartnercompanies",
            name="partner_company",
        ),
        migrations.RemoveField(
            model_name="projectpartnercompanies",
            name="project",
        ),
        migrations.AddField(
            model_name="project",
            name="affiliations",
            field=models.ManyToManyField(
                related_name="affiliated_projects", to="UNRCE_APP.organisation"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="contributing_organizations",
            field=models.ManyToManyField(
                related_name="contributing_projects", to="UNRCE_APP.organisation"
            ),
        ),
        migrations.DeleteModel(
            name="Affiliation",
        ),
        migrations.DeleteModel(
            name="ProjectPartnerCompanies",
        ),
    ]
