# Generated by Django 4.2.4 on 2023-10-02 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("UNRCE_APP", "0006_customuser_interested_sdgs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisation",
            name="address",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="hub",
        ),
        migrations.RemoveField(
            model_name="project",
            name="affiliations",
        ),
        migrations.AddField(
            model_name="customuser",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="UNRCE_APP.organisation",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="rce_hub",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="UNRCE_APP.rcehub",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_name",
            field=models.CharField(default="user", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organisation",
            name="contact_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="organisation_images/"
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="website_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="main_organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="UNRCE_APP.organisation",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="rce_hub",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="UNRCE_APP.rcehub",
            ),
        ),
        migrations.AddField(
            model_name="rcehub",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="audience",
            field=models.CharField(
                choices=[
                    ("general", "General public (any age)"),
                    ("target", "Particular target Audience (Please specify)"),
                    ("adults", "Adults"),
                    ("tertiary", "Tertiary students"),
                    ("high_school", "High school age"),
                    ("primary_school", "Primary School age"),
                    ("early_years", "Early years"),
                    ("adults_60", "Adults >60 please"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
