# Generated by Django 4.2.4 on 2023-10-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "UNRCE_APP",
            "0007_remove_organisation_address_remove_organisation_hub_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role_organisation",
            field=models.CharField(default="role", max_length=150),
            preserve_default=False,
        ),
    ]
