# Generated by Django 4.2.4 on 2023-10-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNRCE_APP', '0008_customuser_role_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
