# Generated by Django 4.2.4 on 2023-10-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNRCE_APP', '0009_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='org',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
