# Generated by Django 4.2.4 on 2023-10-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNRCE_APP', '0010_customuser_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='emails_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
