# Generated by Django 4.2.4 on 2023-10-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNRCE_APP', '0011_customuser_emails_enabled_customuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='audience',
            field=models.CharField(choices=[('general', 'General public (any age)'), ('adults', 'Adults'), ('tertiary', 'Tertiary students'), ('high_school', 'High school age'), ('primary_school', 'Primary School age'), ('early_years', 'Early years'), ('adults_60', 'Adults >60'), ('other', 'Other')], default=('monthly', 'Monthly'), max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='delivery_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannually', 'Biannually'), ('annually', 'Annually'), ('ongoing', 'Ongoing'), ('once', 'Once'), ('irregular', 'Opportunistic/Irregularly'), ('on_demand', 'Permanent/On demand')], default=('monthly', 'Monthly'), max_length=20),
        ),
    ]
