# Generated by Django 4.2.4 on 2023-10-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNRCE_APP', '0011_customuser_emails_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rce_hub2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
