# Generated by Django 4.2.4 on 2023-10-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNRCE_APP', '0012_customuser_rce_hub2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rce_hub2',
            field=models.CharField(blank=True, choices=[('Great Southern', 'Great Southern'), ('Perth Metro', 'Perth Metro')], default='', max_length=255),
        ),
    ]
