# Generated by Django 4.2.4 on 2023-10-17 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNRCE_APP', '0012_alter_project_audience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='interested_users',
            field=models.ManyToManyField(related_name='interested_in_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
