# Generated by Django 4.2.4 on 2023-10-18 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UNRCE_APP', '0014_alter_project_project_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='project_cover_image',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
